import { type Company } from '../types'

export const demoCompany: Company = {
  id: 'company-abc-logistica',
  cnpj: '12.345.678/0001-90',
  legalName: 'ABC Logística LTDA',
  tradeName: 'ABC Logística',
  registrationStatus: 'Ativa',
  openingDate: '14/03/2018',
  legalNature: 'Sociedade Empresária Limitada',
  primaryCnae: '52.11-7-99 — Depósitos de mercadorias para terceiros',
  cep: '50000-000',
  address: 'Av. Norte',
  number: '1500',
  complement: '',
  neighborhood: 'Santo Amaro',
  city: 'Recife',
  state: 'PE',
  phone: '(81) 3030-1840',
  mobile: '(81) 99982-1840',
  institutionalEmail: 'contato@abclogistica.com.br',
  processOwner: 'João Carlos da Silva',
  processOwnerRole: 'Representante legal',
}

export const emptyCompany: Company = {
  id: '',
  cnpj: '',
  legalName: '',
  tradeName: '',
  registrationStatus: '',
  openingDate: '',
  legalNature: '',
  primaryCnae: '',
  cep: '',
  address: '',
  number: '',
  complement: '',
  neighborhood: '',
  city: '',
  state: '',
  phone: '',
  mobile: '',
  institutionalEmail: '',
  processOwner: '',
  processOwnerRole: '',
}
