/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AnalysisRouteImport } from './routes/analysis'
import { Route as ClassifierRouteImport } from './routes/classifier'
import { Route as CompaniesRouteImport } from './routes/companies'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as FirstAccessRouteImport } from './routes/first-access'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as InspectionsRouteImport } from './routes/inspections'
import { Route as MapRouteImport } from './routes/map'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as ProcessesRouteImport } from './routes/processes'
import { Route as PublicConsultationRouteImport } from './routes/public-consultation'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as TriageRouteImport } from './routes/triage'
import { Route as AnalysisIndexRouteImport } from './routes/analysis.index'
import { Route as AnalysisProcessIdRouteImport } from './routes/analysis.$processId'
import { Route as CompaniesCompanyIdRouteImport } from './routes/companies/$companyId'
import { Route as CompaniesAvcbRouteImport } from './routes/companies/avcb'
import { Route as CompaniesDdlcbRouteImport } from './routes/companies/ddlcb'
import { Route as CompaniesEmpresasRouteImport } from './routes/companies/empresas'
import { Route as CompaniesNewRouteImport } from './routes/companies/new'
import { Route as CompaniesProcessoRouteImport } from './routes/companies/processo'
import { Route as CompaniesUnitRouteImport } from './routes/companies/unit'
import { Route as CompaniesUnitEditRouteImport } from './routes/companies/unit-edit'
import { Route as CompaniesUnitsRouteImport } from './routes/companies/units'
import { Route as FirstAccessIndexRouteImport } from './routes/first-access/index'
import { Route as InspectionsIndexRouteImport } from './routes/inspections.index'
import { Route as InspectionsProcessIdRouteImport } from './routes/inspections.$processId'
import { Route as ProcessesProcessIdRouteImport } from './routes/processes/$processId'
import { Route as ProcessesAvcbRouteImport } from './routes/processes/avcb'
import { Route as ProcessesNewRouteImport } from './routes/processes/new'
import { Route as SignupIndexRouteImport } from './routes/signup/index'
import { Route as SignupCompanyRouteImport } from './routes/signup/company'
import { Route as SignupCompanySuccessRouteImport } from './routes/signup/company-success'
import { Route as SignupIndividualRouteImport } from './routes/signup/individual'
import { Route as SignupIndividualSuccessRouteImport } from './routes/signup/individual-success'
import { Route as SignupTechnicalResponsibleRouteImport } from './routes/signup/technical-responsible'
import { Route as SignupTechnicalResponsibleSuccessRouteImport } from './routes/signup/technical-responsible-success'
import { Route as TriageIndexRouteImport } from './routes/triage.index'
import { Route as TriageProcessIdRouteImport } from './routes/triage.$processId'
import { Route as TriagemIndexRouteImport } from './routes/triagem/index'
import { Route as TriagemProcessoIdRouteImport } from './routes/triagem/$processoId'
import { Route as CompaniesEventosIndexRouteImport } from './routes/companies/eventos.index'
import { Route as CompaniesEventosNewRouteImport } from './routes/companies/eventos.new'
import { Route as ProcessesProcessIdIndexRouteImport } from './routes/processes/$processId/index'
import { Route as ProcessesProcessIdCertificateRouteImport } from './routes/processes/$processId/certificate'
import { Route as ProcessesProcessIdCompletedRouteImport } from './routes/processes/$processId/completed'
import { Route as ProcessesProcessIdHistoryRouteImport } from './routes/processes/$processId/history'
import { Route as ProcessesNewIndexRouteImport } from './routes/processes/new/index'
import { Route as ProcessesNewAnalyzingRouteImport } from './routes/processes/new/analyzing'
import { Route as ProcessesNewApprovedRouteImport } from './routes/processes/new/approved'
import { Route as ProcessesNewClassificationRouteImport } from './routes/processes/new/classification'
import { Route as ProcessesNewDeclarationRouteImport } from './routes/processes/new/declaration'
import { Route as ProcessesNewDocumentsRouteImport } from './routes/processes/new/documents'
import { Route as ProcessesNewEstablishmentRouteImport } from './routes/processes/new/establishment'
import { Route as ProcessesNewInspectionRouteImport } from './routes/processes/new/inspection'
import { Route as ProcessesNewPaymentRouteImport } from './routes/processes/new/payment'
import { Route as ProcessesNewProcessingRouteImport } from './routes/processes/new/processing'
import { Route as ProcessesNewProtocolRouteImport } from './routes/processes/new/protocol'
import { Route as ProcessesNewRequestRouteImport } from './routes/processes/new/request'
import { Route as ProcessesNewRequirementsRouteImport } from './routes/processes/new/requirements'
import { Route as ProcessesNewResponsibleRouteImport } from './routes/processes/new/responsible'
import { Route as ProcessesNewResultRouteImport } from './routes/processes/new/result'
import { Route as ProcessesNewReviewRouteImport } from './routes/processes/new/review'
import { Route as ProcessesNewSubmitRouteImport } from './routes/processes/new/submit'
import { Route as ProcessesNewValidationRouteImport } from './routes/processes/new/validation'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisRoute = AnalysisRouteImport.update({
  id: '/analysis',
  path: '/analysis',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassifierRoute = ClassifierRouteImport.update({
  id: '/classifier',
  path: '/classifier',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesRoute = CompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const FirstAccessRoute = FirstAccessRouteImport.update({
  id: '/first-access',
  path: '/first-access',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const InspectionsRoute = InspectionsRouteImport.update({
  id: '/inspections',
  path: '/inspections',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessesRoute = ProcessesRouteImport.update({
  id: '/processes',
  path: '/processes',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicConsultationRoute = PublicConsultationRouteImport.update({
  id: '/public-consultation',
  path: '/public-consultation',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const TriageRoute = TriageRouteImport.update({
  id: '/triage',
  path: '/triage',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalysisIndexRoute = AnalysisIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AnalysisRoute,
} as any)
const AnalysisProcessIdRoute = AnalysisProcessIdRouteImport.update({
  id: '/$processId',
  path: '/$processId',
  getParentRoute: () => AnalysisRoute,
} as any)
const CompaniesCompanyIdRoute = CompaniesCompanyIdRouteImport.update({
  id: '/$companyId',
  path: '/$companyId',
  getParentRoute: () => CompaniesRoute,
} as any)
const CompaniesAvcbRoute = CompaniesAvcbRouteImport.update({
  id: '/avcb',
  path: '/avcb',
  getParentRoute: () => CompaniesRoute,
} as any)
const CompaniesDdlcbRoute = CompaniesDdlcbRouteImport.update({
  id: '/ddlcb',
  path: '/ddlcb',
  getParentRoute: () => CompaniesRoute,
} as any)
const CompaniesEmpresasRoute = CompaniesEmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => CompaniesRoute,
} as any)
const CompaniesNewRoute = CompaniesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => CompaniesRoute,
} as any)
const CompaniesProcessoRoute = CompaniesProcessoRouteImport.update({
  id: '/processo',
  path: '/processo',
  getParentRoute: () => CompaniesRoute,
} as any)
const CompaniesUnitRoute = CompaniesUnitRouteImport.update({
  id: '/unit',
  path: '/unit',
  getParentRoute: () => CompaniesRoute,
} as any)
const CompaniesUnitEditRoute = CompaniesUnitEditRouteImport.update({
  id: '/unit-edit',
  path: '/unit-edit',
  getParentRoute: () => CompaniesRoute,
} as any)
const CompaniesUnitsRoute = CompaniesUnitsRouteImport.update({
  id: '/units',
  path: '/units',
  getParentRoute: () => CompaniesRoute,
} as any)
const FirstAccessIndexRoute = FirstAccessIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FirstAccessRoute,
} as any)
const InspectionsIndexRoute = InspectionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InspectionsRoute,
} as any)
const InspectionsProcessIdRoute = InspectionsProcessIdRouteImport.update({
  id: '/$processId',
  path: '/$processId',
  getParentRoute: () => InspectionsRoute,
} as any)
const ProcessesProcessIdRoute = ProcessesProcessIdRouteImport.update({
  id: '/$processId',
  path: '/$processId',
  getParentRoute: () => ProcessesRoute,
} as any)
const ProcessesAvcbRoute = ProcessesAvcbRouteImport.update({
  id: '/avcb',
  path: '/avcb',
  getParentRoute: () => ProcessesRoute,
} as any)
const ProcessesNewRoute = ProcessesNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => ProcessesRoute,
} as any)
const SignupIndexRoute = SignupIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SignupRoute,
} as any)
const SignupCompanyRoute = SignupCompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => SignupRoute,
} as any)
const SignupCompanySuccessRoute = SignupCompanySuccessRouteImport.update({
  id: '/company-success',
  path: '/company-success',
  getParentRoute: () => SignupRoute,
} as any)
const SignupIndividualRoute = SignupIndividualRouteImport.update({
  id: '/individual',
  path: '/individual',
  getParentRoute: () => SignupRoute,
} as any)
const SignupIndividualSuccessRoute = SignupIndividualSuccessRouteImport.update({
  id: '/individual-success',
  path: '/individual-success',
  getParentRoute: () => SignupRoute,
} as any)
const SignupTechnicalResponsibleRoute =
  SignupTechnicalResponsibleRouteImport.update({
    id: '/technical-responsible',
    path: '/technical-responsible',
    getParentRoute: () => SignupRoute,
  } as any)
const SignupTechnicalResponsibleSuccessRoute =
  SignupTechnicalResponsibleSuccessRouteImport.update({
    id: '/technical-responsible-success',
    path: '/technical-responsible-success',
    getParentRoute: () => SignupRoute,
  } as any)
const TriageIndexRoute = TriageIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TriageRoute,
} as any)
const TriageProcessIdRoute = TriageProcessIdRouteImport.update({
  id: '/$processId',
  path: '/$processId',
  getParentRoute: () => TriageRoute,
} as any)
const TriagemIndexRoute = TriagemIndexRouteImport.update({
  id: '/triagem/',
  path: '/triagem/',
  getParentRoute: () => rootRouteImport,
} as any)
const TriagemProcessoIdRoute = TriagemProcessoIdRouteImport.update({
  id: '/triagem/$processoId',
  path: '/triagem/$processoId',
  getParentRoute: () => rootRouteImport,
} as any)
const CompaniesEventosIndexRoute = CompaniesEventosIndexRouteImport.update({
  id: '/eventos/',
  path: '/eventos/',
  getParentRoute: () => CompaniesRoute,
} as any)
const CompaniesEventosNewRoute = CompaniesEventosNewRouteImport.update({
  id: '/eventos/new',
  path: '/eventos/new',
  getParentRoute: () => CompaniesRoute,
} as any)
const ProcessesProcessIdIndexRoute = ProcessesProcessIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProcessesProcessIdRoute,
} as any)
const ProcessesProcessIdCertificateRoute =
  ProcessesProcessIdCertificateRouteImport.update({
    id: '/certificate',
    path: '/certificate',
    getParentRoute: () => ProcessesProcessIdRoute,
  } as any)
const ProcessesProcessIdCompletedRoute =
  ProcessesProcessIdCompletedRouteImport.update({
    id: '/completed',
    path: '/completed',
    getParentRoute: () => ProcessesProcessIdRoute,
  } as any)
const ProcessesProcessIdHistoryRoute =
  ProcessesProcessIdHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => ProcessesProcessIdRoute,
  } as any)
const ProcessesNewIndexRoute = ProcessesNewIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProcessesNewRoute,
} as any)
const ProcessesNewAnalyzingRoute = ProcessesNewAnalyzingRouteImport.update({
  id: '/analyzing',
  path: '/analyzing',
  getParentRoute: () => ProcessesNewRoute,
} as any)
const ProcessesNewApprovedRoute = ProcessesNewApprovedRouteImport.update({
  id: '/approved',
  path: '/approved',
  getParentRoute: () => ProcessesNewRoute,
} as any)
const ProcessesNewClassificationRoute =
  ProcessesNewClassificationRouteImport.update({
    id: '/classification',
    path: '/classification',
    getParentRoute: () => ProcessesNewRoute,
  } as any)
const ProcessesNewDeclarationRoute = ProcessesNewDeclarationRouteImport.update({
  id: '/declaration',
  path: '/declaration',
  getParentRoute: () => ProcessesNewRoute,
} as any)
const ProcessesNewDocumentsRoute = ProcessesNewDocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => ProcessesNewRoute,
} as any)
const ProcessesNewEstablishmentRoute =
  ProcessesNewEstablishmentRouteImport.update({
    id: '/establishment',
    path: '/establishment',
    getParentRoute: () => ProcessesNewRoute,
  } as any)
const ProcessesNewInspectionRoute = ProcessesNewInspectionRouteImport.update({
  id: '/inspection',
  path: '/inspection',
  getParentRoute: () => ProcessesNewRoute,
} as any)
const ProcessesNewPaymentRoute = ProcessesNewPaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => ProcessesNewRoute,
} as any)
const ProcessesNewProcessingRoute = ProcessesNewProcessingRouteImport.update({
  id: '/processing',
  path: '/processing',
  getParentRoute: () => ProcessesNewRoute,
} as any)
const ProcessesNewProtocolRoute = ProcessesNewProtocolRouteImport.update({
  id: '/protocol',
  path: '/protocol',
  getParentRoute: () => ProcessesNewRoute,
} as any)
const ProcessesNewRequestRoute = ProcessesNewRequestRouteImport.update({
  id: '/request',
  path: '/request',
  getParentRoute: () => ProcessesNewRoute,
} as any)
const ProcessesNewRequirementsRoute =
  ProcessesNewRequirementsRouteImport.update({
    id: '/requirements',
    path: '/requirements',
    getParentRoute: () => ProcessesNewRoute,
  } as any)
const ProcessesNewResponsibleRoute = ProcessesNewResponsibleRouteImport.update({
  id: '/responsible',
  path: '/responsible',
  getParentRoute: () => ProcessesNewRoute,
} as any)
const ProcessesNewResultRoute = ProcessesNewResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => ProcessesNewRoute,
} as any)
const ProcessesNewReviewRoute = ProcessesNewReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => ProcessesNewRoute,
} as any)
const ProcessesNewSubmitRoute = ProcessesNewSubmitRouteImport.update({
  id: '/submit',
  path: '/submit',
  getParentRoute: () => ProcessesNewRoute,
} as any)
const ProcessesNewValidationRoute = ProcessesNewValidationRouteImport.update({
  id: '/validation',
  path: '/validation',
  getParentRoute: () => ProcessesNewRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/analysis': typeof AnalysisRouteWithChildren
  '/classifier': typeof ClassifierRoute
  '/companies': typeof CompaniesRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRoute
  '/first-access': typeof FirstAccessRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/inspections': typeof InspectionsRouteWithChildren
  '/map': typeof MapRoute
  '/notifications': typeof NotificationsRoute
  '/processes': typeof ProcessesRouteWithChildren
  '/public-consultation': typeof PublicConsultationRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRouteWithChildren
  '/triage': typeof TriageRouteWithChildren
  '/analysis/$processId': typeof AnalysisProcessIdRoute
  '/companies/$companyId': typeof CompaniesCompanyIdRoute
  '/companies/avcb': typeof CompaniesAvcbRoute
  '/companies/ddlcb': typeof CompaniesDdlcbRoute
  '/companies/empresas': typeof CompaniesEmpresasRoute
  '/companies/new': typeof CompaniesNewRoute
  '/companies/processo': typeof CompaniesProcessoRoute
  '/companies/unit': typeof CompaniesUnitRoute
  '/companies/unit-edit': typeof CompaniesUnitEditRoute
  '/companies/units': typeof CompaniesUnitsRoute
  '/inspections/$processId': typeof InspectionsProcessIdRoute
  '/processes/$processId': typeof ProcessesProcessIdRouteWithChildren
  '/processes/avcb': typeof ProcessesAvcbRoute
  '/processes/new': typeof ProcessesNewRouteWithChildren
  '/signup/company': typeof SignupCompanyRoute
  '/signup/company-success': typeof SignupCompanySuccessRoute
  '/signup/individual': typeof SignupIndividualRoute
  '/signup/individual-success': typeof SignupIndividualSuccessRoute
  '/signup/technical-responsible': typeof SignupTechnicalResponsibleRoute
  '/signup/technical-responsible-success': typeof SignupTechnicalResponsibleSuccessRoute
  '/triage/$processId': typeof TriageProcessIdRoute
  '/triagem/$processoId': typeof TriagemProcessoIdRoute
  '/analysis/': typeof AnalysisIndexRoute
  '/first-access/': typeof FirstAccessIndexRoute
  '/inspections/': typeof InspectionsIndexRoute
  '/signup/': typeof SignupIndexRoute
  '/triage/': typeof TriageIndexRoute
  '/triagem/': typeof TriagemIndexRoute
  '/companies/eventos/new': typeof CompaniesEventosNewRoute
  '/processes/$processId/certificate': typeof ProcessesProcessIdCertificateRoute
  '/processes/$processId/completed': typeof ProcessesProcessIdCompletedRoute
  '/processes/$processId/history': typeof ProcessesProcessIdHistoryRoute
  '/processes/new/analyzing': typeof ProcessesNewAnalyzingRoute
  '/processes/new/approved': typeof ProcessesNewApprovedRoute
  '/processes/new/classification': typeof ProcessesNewClassificationRoute
  '/processes/new/declaration': typeof ProcessesNewDeclarationRoute
  '/processes/new/documents': typeof ProcessesNewDocumentsRoute
  '/processes/new/establishment': typeof ProcessesNewEstablishmentRoute
  '/processes/new/inspection': typeof ProcessesNewInspectionRoute
  '/processes/new/payment': typeof ProcessesNewPaymentRoute
  '/processes/new/processing': typeof ProcessesNewProcessingRoute
  '/processes/new/protocol': typeof ProcessesNewProtocolRoute
  '/processes/new/request': typeof ProcessesNewRequestRoute
  '/processes/new/requirements': typeof ProcessesNewRequirementsRoute
  '/processes/new/responsible': typeof ProcessesNewResponsibleRoute
  '/processes/new/result': typeof ProcessesNewResultRoute
  '/processes/new/review': typeof ProcessesNewReviewRoute
  '/processes/new/submit': typeof ProcessesNewSubmitRoute
  '/processes/new/validation': typeof ProcessesNewValidationRoute
  '/companies/eventos/': typeof CompaniesEventosIndexRoute
  '/processes/$processId/': typeof ProcessesProcessIdIndexRoute
  '/processes/new/': typeof ProcessesNewIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/classifier': typeof ClassifierRoute
  '/companies': typeof CompaniesRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/map': typeof MapRoute
  '/notifications': typeof NotificationsRoute
  '/processes': typeof ProcessesRouteWithChildren
  '/public-consultation': typeof PublicConsultationRoute
  '/signin': typeof SigninRoute
  '/analysis/$processId': typeof AnalysisProcessIdRoute
  '/companies/$companyId': typeof CompaniesCompanyIdRoute
  '/companies/avcb': typeof CompaniesAvcbRoute
  '/companies/ddlcb': typeof CompaniesDdlcbRoute
  '/companies/empresas': typeof CompaniesEmpresasRoute
  '/companies/new': typeof CompaniesNewRoute
  '/companies/processo': typeof CompaniesProcessoRoute
  '/companies/unit': typeof CompaniesUnitRoute
  '/companies/unit-edit': typeof CompaniesUnitEditRoute
  '/companies/units': typeof CompaniesUnitsRoute
  '/inspections/$processId': typeof InspectionsProcessIdRoute
  '/processes/avcb': typeof ProcessesAvcbRoute
  '/signup/company': typeof SignupCompanyRoute
  '/signup/company-success': typeof SignupCompanySuccessRoute
  '/signup/individual': typeof SignupIndividualRoute
  '/signup/individual-success': typeof SignupIndividualSuccessRoute
  '/signup/technical-responsible': typeof SignupTechnicalResponsibleRoute
  '/signup/technical-responsible-success': typeof SignupTechnicalResponsibleSuccessRoute
  '/triage/$processId': typeof TriageProcessIdRoute
  '/triagem/$processoId': typeof TriagemProcessoIdRoute
  '/analysis': typeof AnalysisIndexRoute
  '/first-access': typeof FirstAccessIndexRoute
  '/inspections': typeof InspectionsIndexRoute
  '/signup': typeof SignupIndexRoute
  '/triage': typeof TriageIndexRoute
  '/triagem': typeof TriagemIndexRoute
  '/companies/eventos/new': typeof CompaniesEventosNewRoute
  '/processes/$processId/certificate': typeof ProcessesProcessIdCertificateRoute
  '/processes/$processId/completed': typeof ProcessesProcessIdCompletedRoute
  '/processes/$processId/history': typeof ProcessesProcessIdHistoryRoute
  '/processes/new/analyzing': typeof ProcessesNewAnalyzingRoute
  '/processes/new/approved': typeof ProcessesNewApprovedRoute
  '/processes/new/classification': typeof ProcessesNewClassificationRoute
  '/processes/new/declaration': typeof ProcessesNewDeclarationRoute
  '/processes/new/documents': typeof ProcessesNewDocumentsRoute
  '/processes/new/establishment': typeof ProcessesNewEstablishmentRoute
  '/processes/new/inspection': typeof ProcessesNewInspectionRoute
  '/processes/new/payment': typeof ProcessesNewPaymentRoute
  '/processes/new/processing': typeof ProcessesNewProcessingRoute
  '/processes/new/protocol': typeof ProcessesNewProtocolRoute
  '/processes/new/request': typeof ProcessesNewRequestRoute
  '/processes/new/requirements': typeof ProcessesNewRequirementsRoute
  '/processes/new/responsible': typeof ProcessesNewResponsibleRoute
  '/processes/new/result': typeof ProcessesNewResultRoute
  '/processes/new/review': typeof ProcessesNewReviewRoute
  '/processes/new/submit': typeof ProcessesNewSubmitRoute
  '/processes/new/validation': typeof ProcessesNewValidationRoute
  '/companies/eventos': typeof CompaniesEventosIndexRoute
  '/processes/$processId': typeof ProcessesProcessIdIndexRoute
  '/processes/new': typeof ProcessesNewIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/analysis': typeof AnalysisRouteWithChildren
  '/classifier': typeof ClassifierRoute
  '/companies': typeof CompaniesRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/documents': typeof DocumentsRoute
  '/first-access': typeof FirstAccessRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/inspections': typeof InspectionsRouteWithChildren
  '/map': typeof MapRoute
  '/notifications': typeof NotificationsRoute
  '/processes': typeof ProcessesRouteWithChildren
  '/public-consultation': typeof PublicConsultationRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRouteWithChildren
  '/triage': typeof TriageRouteWithChildren
  '/analysis/$processId': typeof AnalysisProcessIdRoute
  '/companies/$companyId': typeof CompaniesCompanyIdRoute
  '/companies/avcb': typeof CompaniesAvcbRoute
  '/companies/ddlcb': typeof CompaniesDdlcbRoute
  '/companies/empresas': typeof CompaniesEmpresasRoute
  '/companies/new': typeof CompaniesNewRoute
  '/companies/processo': typeof CompaniesProcessoRoute
  '/companies/unit': typeof CompaniesUnitRoute
  '/companies/unit-edit': typeof CompaniesUnitEditRoute
  '/companies/units': typeof CompaniesUnitsRoute
  '/inspections/$processId': typeof InspectionsProcessIdRoute
  '/processes/$processId': typeof ProcessesProcessIdRouteWithChildren
  '/processes/avcb': typeof ProcessesAvcbRoute
  '/processes/new': typeof ProcessesNewRouteWithChildren
  '/signup/company': typeof SignupCompanyRoute
  '/signup/company-success': typeof SignupCompanySuccessRoute
  '/signup/individual': typeof SignupIndividualRoute
  '/signup/individual-success': typeof SignupIndividualSuccessRoute
  '/signup/technical-responsible': typeof SignupTechnicalResponsibleRoute
  '/signup/technical-responsible-success': typeof SignupTechnicalResponsibleSuccessRoute
  '/triage/$processId': typeof TriageProcessIdRoute
  '/triagem/$processoId': typeof TriagemProcessoIdRoute
  '/analysis/': typeof AnalysisIndexRoute
  '/first-access/': typeof FirstAccessIndexRoute
  '/inspections/': typeof InspectionsIndexRoute
  '/signup/': typeof SignupIndexRoute
  '/triage/': typeof TriageIndexRoute
  '/triagem/': typeof TriagemIndexRoute
  '/companies/eventos/new': typeof CompaniesEventosNewRoute
  '/processes/$processId/certificate': typeof ProcessesProcessIdCertificateRoute
  '/processes/$processId/completed': typeof ProcessesProcessIdCompletedRoute
  '/processes/$processId/history': typeof ProcessesProcessIdHistoryRoute
  '/processes/new/analyzing': typeof ProcessesNewAnalyzingRoute
  '/processes/new/approved': typeof ProcessesNewApprovedRoute
  '/processes/new/classification': typeof ProcessesNewClassificationRoute
  '/processes/new/declaration': typeof ProcessesNewDeclarationRoute
  '/processes/new/documents': typeof ProcessesNewDocumentsRoute
  '/processes/new/establishment': typeof ProcessesNewEstablishmentRoute
  '/processes/new/inspection': typeof ProcessesNewInspectionRoute
  '/processes/new/payment': typeof ProcessesNewPaymentRoute
  '/processes/new/processing': typeof ProcessesNewProcessingRoute
  '/processes/new/protocol': typeof ProcessesNewProtocolRoute
  '/processes/new/request': typeof ProcessesNewRequestRoute
  '/processes/new/requirements': typeof ProcessesNewRequirementsRoute
  '/processes/new/responsible': typeof ProcessesNewResponsibleRoute
  '/processes/new/result': typeof ProcessesNewResultRoute
  '/processes/new/review': typeof ProcessesNewReviewRoute
  '/processes/new/submit': typeof ProcessesNewSubmitRoute
  '/processes/new/validation': typeof ProcessesNewValidationRoute
  '/companies/eventos/': typeof CompaniesEventosIndexRoute
  '/processes/$processId/': typeof ProcessesProcessIdIndexRoute
  '/processes/new/': typeof ProcessesNewIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/analysis'
    | '/classifier'
    | '/companies'
    | '/dashboard'
    | '/documents'
    | '/first-access'
    | '/forgot-password'
    | '/inspections'
    | '/map'
    | '/notifications'
    | '/processes'
    | '/public-consultation'
    | '/signin'
    | '/signup'
    | '/triage'
    | '/analysis/$processId'
    | '/companies/$companyId'
    | '/companies/avcb'
    | '/companies/ddlcb'
    | '/companies/empresas'
    | '/companies/new'
    | '/companies/processo'
    | '/companies/unit'
    | '/companies/unit-edit'
    | '/companies/units'
    | '/inspections/$processId'
    | '/processes/$processId'
    | '/processes/avcb'
    | '/processes/new'
    | '/signup/company'
    | '/signup/company-success'
    | '/signup/individual'
    | '/signup/individual-success'
    | '/signup/technical-responsible'
    | '/signup/technical-responsible-success'
    | '/triage/$processId'
    | '/triagem/$processoId'
    | '/analysis/'
    | '/first-access/'
    | '/inspections/'
    | '/signup/'
    | '/triage/'
    | '/triagem/'
    | '/companies/eventos/new'
    | '/processes/$processId/certificate'
    | '/processes/$processId/completed'
    | '/processes/$processId/history'
    | '/processes/new/analyzing'
    | '/processes/new/approved'
    | '/processes/new/classification'
    | '/processes/new/declaration'
    | '/processes/new/documents'
    | '/processes/new/establishment'
    | '/processes/new/inspection'
    | '/processes/new/payment'
    | '/processes/new/processing'
    | '/processes/new/protocol'
    | '/processes/new/request'
    | '/processes/new/requirements'
    | '/processes/new/responsible'
    | '/processes/new/result'
    | '/processes/new/review'
    | '/processes/new/submit'
    | '/processes/new/validation'
    | '/companies/eventos/'
    | '/processes/$processId/'
    | '/processes/new/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/classifier'
    | '/companies'
    | '/dashboard'
    | '/documents'
    | '/forgot-password'
    | '/map'
    | '/notifications'
    | '/processes'
    | '/public-consultation'
    | '/signin'
    | '/analysis/$processId'
    | '/companies/$companyId'
    | '/companies/avcb'
    | '/companies/ddlcb'
    | '/companies/empresas'
    | '/companies/new'
    | '/companies/processo'
    | '/companies/unit'
    | '/companies/unit-edit'
    | '/companies/units'
    | '/inspections/$processId'
    | '/processes/avcb'
    | '/signup/company'
    | '/signup/company-success'
    | '/signup/individual'
    | '/signup/individual-success'
    | '/signup/technical-responsible'
    | '/signup/technical-responsible-success'
    | '/triage/$processId'
    | '/triagem/$processoId'
    | '/analysis'
    | '/first-access'
    | '/inspections'
    | '/signup'
    | '/triage'
    | '/triagem'
    | '/companies/eventos/new'
    | '/processes/$processId/certificate'
    | '/processes/$processId/completed'
    | '/processes/$processId/history'
    | '/processes/new/analyzing'
    | '/processes/new/approved'
    | '/processes/new/classification'
    | '/processes/new/declaration'
    | '/processes/new/documents'
    | '/processes/new/establishment'
    | '/processes/new/inspection'
    | '/processes/new/payment'
    | '/processes/new/processing'
    | '/processes/new/protocol'
    | '/processes/new/request'
    | '/processes/new/requirements'
    | '/processes/new/responsible'
    | '/processes/new/result'
    | '/processes/new/review'
    | '/processes/new/submit'
    | '/processes/new/validation'
    | '/companies/eventos'
    | '/processes/$processId'
    | '/processes/new'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/analysis'
    | '/classifier'
    | '/companies'
    | '/dashboard'
    | '/documents'
    | '/first-access'
    | '/forgot-password'
    | '/inspections'
    | '/map'
    | '/notifications'
    | '/processes'
    | '/public-consultation'
    | '/signin'
    | '/signup'
    | '/triage'
    | '/analysis/$processId'
    | '/companies/$companyId'
    | '/companies/avcb'
    | '/companies/ddlcb'
    | '/companies/empresas'
    | '/companies/new'
    | '/companies/processo'
    | '/companies/unit'
    | '/companies/unit-edit'
    | '/companies/units'
    | '/inspections/$processId'
    | '/processes/$processId'
    | '/processes/avcb'
    | '/processes/new'
    | '/signup/company'
    | '/signup/company-success'
    | '/signup/individual'
    | '/signup/individual-success'
    | '/signup/technical-responsible'
    | '/signup/technical-responsible-success'
    | '/triage/$processId'
    | '/triagem/$processoId'
    | '/analysis/'
    | '/first-access/'
    | '/inspections/'
    | '/signup/'
    | '/triage/'
    | '/triagem/'
    | '/companies/eventos/new'
    | '/processes/$processId/certificate'
    | '/processes/$processId/completed'
    | '/processes/$processId/history'
    | '/processes/new/analyzing'
    | '/processes/new/approved'
    | '/processes/new/classification'
    | '/processes/new/declaration'
    | '/processes/new/documents'
    | '/processes/new/establishment'
    | '/processes/new/inspection'
    | '/processes/new/payment'
    | '/processes/new/processing'
    | '/processes/new/protocol'
    | '/processes/new/request'
    | '/processes/new/requirements'
    | '/processes/new/responsible'
    | '/processes/new/result'
    | '/processes/new/review'
    | '/processes/new/submit'
    | '/processes/new/validation'
    | '/companies/eventos/'
    | '/processes/$processId/'
    | '/processes/new/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AnalysisRoute: typeof AnalysisRouteWithChildren
  ClassifierRoute: typeof ClassifierRoute
  CompaniesRoute: typeof CompaniesRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  DocumentsRoute: typeof DocumentsRoute
  FirstAccessRoute: typeof FirstAccessRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  InspectionsRoute: typeof InspectionsRouteWithChildren
  MapRoute: typeof MapRoute
  NotificationsRoute: typeof NotificationsRoute
  ProcessesRoute: typeof ProcessesRouteWithChildren
  PublicConsultationRoute: typeof PublicConsultationRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRouteWithChildren
  TriageRoute: typeof TriageRouteWithChildren
  TriagemProcessoIdRoute: typeof TriagemProcessoIdRoute
  TriagemIndexRoute: typeof TriagemIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis': {
      id: '/analysis'
      path: '/analysis'
      fullPath: '/analysis'
      preLoaderRoute: typeof AnalysisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classifier': {
      id: '/classifier'
      path: '/classifier'
      fullPath: '/classifier'
      preLoaderRoute: typeof ClassifierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies': {
      id: '/companies'
      path: '/companies'
      fullPath: '/companies'
      preLoaderRoute: typeof CompaniesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/first-access': {
      id: '/first-access'
      path: '/first-access'
      fullPath: '/first-access'
      preLoaderRoute: typeof FirstAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inspections': {
      id: '/inspections'
      path: '/inspections'
      fullPath: '/inspections'
      preLoaderRoute: typeof InspectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/processes': {
      id: '/processes'
      path: '/processes'
      fullPath: '/processes'
      preLoaderRoute: typeof ProcessesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/public-consultation': {
      id: '/public-consultation'
      path: '/public-consultation'
      fullPath: '/public-consultation'
      preLoaderRoute: typeof PublicConsultationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/triage': {
      id: '/triage'
      path: '/triage'
      fullPath: '/triage'
      preLoaderRoute: typeof TriageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analysis/': {
      id: '/analysis/'
      path: '/'
      fullPath: '/analysis/'
      preLoaderRoute: typeof AnalysisIndexRouteImport
      parentRoute: typeof AnalysisRoute
    }
    '/analysis/$processId': {
      id: '/analysis/$processId'
      path: '/$processId'
      fullPath: '/analysis/$processId'
      preLoaderRoute: typeof AnalysisProcessIdRouteImport
      parentRoute: typeof AnalysisRoute
    }
    '/companies/$companyId': {
      id: '/companies/$companyId'
      path: '/$companyId'
      fullPath: '/companies/$companyId'
      preLoaderRoute: typeof CompaniesCompanyIdRouteImport
      parentRoute: typeof CompaniesRoute
    }
    '/companies/avcb': {
      id: '/companies/avcb'
      path: '/avcb'
      fullPath: '/companies/avcb'
      preLoaderRoute: typeof CompaniesAvcbRouteImport
      parentRoute: typeof CompaniesRoute
    }
    '/companies/ddlcb': {
      id: '/companies/ddlcb'
      path: '/ddlcb'
      fullPath: '/companies/ddlcb'
      preLoaderRoute: typeof CompaniesDdlcbRouteImport
      parentRoute: typeof CompaniesRoute
    }
    '/companies/empresas': {
      id: '/companies/empresas'
      path: '/empresas'
      fullPath: '/companies/empresas'
      preLoaderRoute: typeof CompaniesEmpresasRouteImport
      parentRoute: typeof CompaniesRoute
    }
    '/companies/new': {
      id: '/companies/new'
      path: '/new'
      fullPath: '/companies/new'
      preLoaderRoute: typeof CompaniesNewRouteImport
      parentRoute: typeof CompaniesRoute
    }
    '/companies/processo': {
      id: '/companies/processo'
      path: '/processo'
      fullPath: '/companies/processo'
      preLoaderRoute: typeof CompaniesProcessoRouteImport
      parentRoute: typeof CompaniesRoute
    }
    '/companies/unit': {
      id: '/companies/unit'
      path: '/unit'
      fullPath: '/companies/unit'
      preLoaderRoute: typeof CompaniesUnitRouteImport
      parentRoute: typeof CompaniesRoute
    }
    '/companies/unit-edit': {
      id: '/companies/unit-edit'
      path: '/unit-edit'
      fullPath: '/companies/unit-edit'
      preLoaderRoute: typeof CompaniesUnitEditRouteImport
      parentRoute: typeof CompaniesRoute
    }
    '/companies/units': {
      id: '/companies/units'
      path: '/units'
      fullPath: '/companies/units'
      preLoaderRoute: typeof CompaniesUnitsRouteImport
      parentRoute: typeof CompaniesRoute
    }
    '/first-access/': {
      id: '/first-access/'
      path: '/'
      fullPath: '/first-access/'
      preLoaderRoute: typeof FirstAccessIndexRouteImport
      parentRoute: typeof FirstAccessRoute
    }
    '/inspections/': {
      id: '/inspections/'
      path: '/'
      fullPath: '/inspections/'
      preLoaderRoute: typeof InspectionsIndexRouteImport
      parentRoute: typeof InspectionsRoute
    }
    '/inspections/$processId': {
      id: '/inspections/$processId'
      path: '/$processId'
      fullPath: '/inspections/$processId'
      preLoaderRoute: typeof InspectionsProcessIdRouteImport
      parentRoute: typeof InspectionsRoute
    }
    '/processes/$processId': {
      id: '/processes/$processId'
      path: '/$processId'
      fullPath: '/processes/$processId'
      preLoaderRoute: typeof ProcessesProcessIdRouteImport
      parentRoute: typeof ProcessesRoute
    }
    '/processes/avcb': {
      id: '/processes/avcb'
      path: '/avcb'
      fullPath: '/processes/avcb'
      preLoaderRoute: typeof ProcessesAvcbRouteImport
      parentRoute: typeof ProcessesRoute
    }
    '/processes/new': {
      id: '/processes/new'
      path: '/new'
      fullPath: '/processes/new'
      preLoaderRoute: typeof ProcessesNewRouteImport
      parentRoute: typeof ProcessesRoute
    }
    '/signup/': {
      id: '/signup/'
      path: '/'
      fullPath: '/signup/'
      preLoaderRoute: typeof SignupIndexRouteImport
      parentRoute: typeof SignupRoute
    }
    '/signup/company': {
      id: '/signup/company'
      path: '/company'
      fullPath: '/signup/company'
      preLoaderRoute: typeof SignupCompanyRouteImport
      parentRoute: typeof SignupRoute
    }
    '/signup/company-success': {
      id: '/signup/company-success'
      path: '/company-success'
      fullPath: '/signup/company-success'
      preLoaderRoute: typeof SignupCompanySuccessRouteImport
      parentRoute: typeof SignupRoute
    }
    '/signup/individual': {
      id: '/signup/individual'
      path: '/individual'
      fullPath: '/signup/individual'
      preLoaderRoute: typeof SignupIndividualRouteImport
      parentRoute: typeof SignupRoute
    }
    '/signup/individual-success': {
      id: '/signup/individual-success'
      path: '/individual-success'
      fullPath: '/signup/individual-success'
      preLoaderRoute: typeof SignupIndividualSuccessRouteImport
      parentRoute: typeof SignupRoute
    }
    '/signup/technical-responsible': {
      id: '/signup/technical-responsible'
      path: '/technical-responsible'
      fullPath: '/signup/technical-responsible'
      preLoaderRoute: typeof SignupTechnicalResponsibleRouteImport
      parentRoute: typeof SignupRoute
    }
    '/signup/technical-responsible-success': {
      id: '/signup/technical-responsible-success'
      path: '/technical-responsible-success'
      fullPath: '/signup/technical-responsible-success'
      preLoaderRoute: typeof SignupTechnicalResponsibleSuccessRouteImport
      parentRoute: typeof SignupRoute
    }
    '/triage/': {
      id: '/triage/'
      path: '/'
      fullPath: '/triage/'
      preLoaderRoute: typeof TriageIndexRouteImport
      parentRoute: typeof TriageRoute
    }
    '/triage/$processId': {
      id: '/triage/$processId'
      path: '/$processId'
      fullPath: '/triage/$processId'
      preLoaderRoute: typeof TriageProcessIdRouteImport
      parentRoute: typeof TriageRoute
    }
    '/triagem/': {
      id: '/triagem/'
      path: '/triagem'
      fullPath: '/triagem/'
      preLoaderRoute: typeof TriagemIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/triagem/$processoId': {
      id: '/triagem/$processoId'
      path: '/triagem/$processoId'
      fullPath: '/triagem/$processoId'
      preLoaderRoute: typeof TriagemProcessoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/companies/eventos/': {
      id: '/companies/eventos/'
      path: '/eventos'
      fullPath: '/companies/eventos/'
      preLoaderRoute: typeof CompaniesEventosIndexRouteImport
      parentRoute: typeof CompaniesRoute
    }
    '/companies/eventos/new': {
      id: '/companies/eventos/new'
      path: '/eventos/new'
      fullPath: '/companies/eventos/new'
      preLoaderRoute: typeof CompaniesEventosNewRouteImport
      parentRoute: typeof CompaniesRoute
    }
    '/processes/$processId/': {
      id: '/processes/$processId/'
      path: '/'
      fullPath: '/processes/$processId/'
      preLoaderRoute: typeof ProcessesProcessIdIndexRouteImport
      parentRoute: typeof ProcessesProcessIdRoute
    }
    '/processes/$processId/certificate': {
      id: '/processes/$processId/certificate'
      path: '/certificate'
      fullPath: '/processes/$processId/certificate'
      preLoaderRoute: typeof ProcessesProcessIdCertificateRouteImport
      parentRoute: typeof ProcessesProcessIdRoute
    }
    '/processes/$processId/completed': {
      id: '/processes/$processId/completed'
      path: '/completed'
      fullPath: '/processes/$processId/completed'
      preLoaderRoute: typeof ProcessesProcessIdCompletedRouteImport
      parentRoute: typeof ProcessesProcessIdRoute
    }
    '/processes/$processId/history': {
      id: '/processes/$processId/history'
      path: '/history'
      fullPath: '/processes/$processId/history'
      preLoaderRoute: typeof ProcessesProcessIdHistoryRouteImport
      parentRoute: typeof ProcessesProcessIdRoute
    }
    '/processes/new/': {
      id: '/processes/new/'
      path: '/'
      fullPath: '/processes/new/'
      preLoaderRoute: typeof ProcessesNewIndexRouteImport
      parentRoute: typeof ProcessesNewRoute
    }
    '/processes/new/analyzing': {
      id: '/processes/new/analyzing'
      path: '/analyzing'
      fullPath: '/processes/new/analyzing'
      preLoaderRoute: typeof ProcessesNewAnalyzingRouteImport
      parentRoute: typeof ProcessesNewRoute
    }
    '/processes/new/approved': {
      id: '/processes/new/approved'
      path: '/approved'
      fullPath: '/processes/new/approved'
      preLoaderRoute: typeof ProcessesNewApprovedRouteImport
      parentRoute: typeof ProcessesNewRoute
    }
    '/processes/new/classification': {
      id: '/processes/new/classification'
      path: '/classification'
      fullPath: '/processes/new/classification'
      preLoaderRoute: typeof ProcessesNewClassificationRouteImport
      parentRoute: typeof ProcessesNewRoute
    }
    '/processes/new/declaration': {
      id: '/processes/new/declaration'
      path: '/declaration'
      fullPath: '/processes/new/declaration'
      preLoaderRoute: typeof ProcessesNewDeclarationRouteImport
      parentRoute: typeof ProcessesNewRoute
    }
    '/processes/new/documents': {
      id: '/processes/new/documents'
      path: '/documents'
      fullPath: '/processes/new/documents'
      preLoaderRoute: typeof ProcessesNewDocumentsRouteImport
      parentRoute: typeof ProcessesNewRoute
    }
    '/processes/new/establishment': {
      id: '/processes/new/establishment'
      path: '/establishment'
      fullPath: '/processes/new/establishment'
      preLoaderRoute: typeof ProcessesNewEstablishmentRouteImport
      parentRoute: typeof ProcessesNewRoute
    }
    '/processes/new/inspection': {
      id: '/processes/new/inspection'
      path: '/inspection'
      fullPath: '/processes/new/inspection'
      preLoaderRoute: typeof ProcessesNewInspectionRouteImport
      parentRoute: typeof ProcessesNewRoute
    }
    '/processes/new/payment': {
      id: '/processes/new/payment'
      path: '/payment'
      fullPath: '/processes/new/payment'
      preLoaderRoute: typeof ProcessesNewPaymentRouteImport
      parentRoute: typeof ProcessesNewRoute
    }
    '/processes/new/processing': {
      id: '/processes/new/processing'
      path: '/processing'
      fullPath: '/processes/new/processing'
      preLoaderRoute: typeof ProcessesNewProcessingRouteImport
      parentRoute: typeof ProcessesNewRoute
    }
    '/processes/new/protocol': {
      id: '/processes/new/protocol'
      path: '/protocol'
      fullPath: '/processes/new/protocol'
      preLoaderRoute: typeof ProcessesNewProtocolRouteImport
      parentRoute: typeof ProcessesNewRoute
    }
    '/processes/new/request': {
      id: '/processes/new/request'
      path: '/request'
      fullPath: '/processes/new/request'
      preLoaderRoute: typeof ProcessesNewRequestRouteImport
      parentRoute: typeof ProcessesNewRoute
    }
    '/processes/new/requirements': {
      id: '/processes/new/requirements'
      path: '/requirements'
      fullPath: '/processes/new/requirements'
      preLoaderRoute: typeof ProcessesNewRequirementsRouteImport
      parentRoute: typeof ProcessesNewRoute
    }
    '/processes/new/responsible': {
      id: '/processes/new/responsible'
      path: '/responsible'
      fullPath: '/processes/new/responsible'
      preLoaderRoute: typeof ProcessesNewResponsibleRouteImport
      parentRoute: typeof ProcessesNewRoute
    }
    '/processes/new/result': {
      id: '/processes/new/result'
      path: '/result'
      fullPath: '/processes/new/result'
      preLoaderRoute: typeof ProcessesNewResultRouteImport
      parentRoute: typeof ProcessesNewRoute
    }
    '/processes/new/review': {
      id: '/processes/new/review'
      path: '/review'
      fullPath: '/processes/new/review'
      preLoaderRoute: typeof ProcessesNewReviewRouteImport
      parentRoute: typeof ProcessesNewRoute
    }
    '/processes/new/submit': {
      id: '/processes/new/submit'
      path: '/submit'
      fullPath: '/processes/new/submit'
      preLoaderRoute: typeof ProcessesNewSubmitRouteImport
      parentRoute: typeof ProcessesNewRoute
    }
    '/processes/new/validation': {
      id: '/processes/new/validation'
      path: '/validation'
      fullPath: '/processes/new/validation'
      preLoaderRoute: typeof ProcessesNewValidationRouteImport
      parentRoute: typeof ProcessesNewRoute
    }
  }
}

interface AnalysisRouteChildren {
  AnalysisProcessIdRoute: typeof AnalysisProcessIdRoute
  AnalysisIndexRoute: typeof AnalysisIndexRoute
}

const AnalysisRouteChildren: AnalysisRouteChildren = {
  AnalysisProcessIdRoute: AnalysisProcessIdRoute,
  AnalysisIndexRoute: AnalysisIndexRoute,
}

const AnalysisRouteWithChildren = AnalysisRoute._addFileChildren(
  AnalysisRouteChildren,
)

interface CompaniesRouteChildren {
  CompaniesCompanyIdRoute: typeof CompaniesCompanyIdRoute
  CompaniesAvcbRoute: typeof CompaniesAvcbRoute
  CompaniesDdlcbRoute: typeof CompaniesDdlcbRoute
  CompaniesEmpresasRoute: typeof CompaniesEmpresasRoute
  CompaniesNewRoute: typeof CompaniesNewRoute
  CompaniesProcessoRoute: typeof CompaniesProcessoRoute
  CompaniesUnitRoute: typeof CompaniesUnitRoute
  CompaniesUnitEditRoute: typeof CompaniesUnitEditRoute
  CompaniesUnitsRoute: typeof CompaniesUnitsRoute
  CompaniesEventosNewRoute: typeof CompaniesEventosNewRoute
  CompaniesEventosIndexRoute: typeof CompaniesEventosIndexRoute
}

const CompaniesRouteChildren: CompaniesRouteChildren = {
  CompaniesCompanyIdRoute: CompaniesCompanyIdRoute,
  CompaniesAvcbRoute: CompaniesAvcbRoute,
  CompaniesDdlcbRoute: CompaniesDdlcbRoute,
  CompaniesEmpresasRoute: CompaniesEmpresasRoute,
  CompaniesNewRoute: CompaniesNewRoute,
  CompaniesProcessoRoute: CompaniesProcessoRoute,
  CompaniesUnitRoute: CompaniesUnitRoute,
  CompaniesUnitEditRoute: CompaniesUnitEditRoute,
  CompaniesUnitsRoute: CompaniesUnitsRoute,
  CompaniesEventosNewRoute: CompaniesEventosNewRoute,
  CompaniesEventosIndexRoute: CompaniesEventosIndexRoute,
}

const CompaniesRouteWithChildren = CompaniesRoute._addFileChildren(
  CompaniesRouteChildren,
)

interface FirstAccessRouteChildren {
  FirstAccessIndexRoute: typeof FirstAccessIndexRoute
}

const FirstAccessRouteChildren: FirstAccessRouteChildren = {
  FirstAccessIndexRoute: FirstAccessIndexRoute,
}

const FirstAccessRouteWithChildren = FirstAccessRoute._addFileChildren(
  FirstAccessRouteChildren,
)

interface InspectionsRouteChildren {
  InspectionsProcessIdRoute: typeof InspectionsProcessIdRoute
  InspectionsIndexRoute: typeof InspectionsIndexRoute
}

const InspectionsRouteChildren: InspectionsRouteChildren = {
  InspectionsProcessIdRoute: InspectionsProcessIdRoute,
  InspectionsIndexRoute: InspectionsIndexRoute,
}

const InspectionsRouteWithChildren = InspectionsRoute._addFileChildren(
  InspectionsRouteChildren,
)

interface ProcessesProcessIdRouteChildren {
  ProcessesProcessIdCertificateRoute: typeof ProcessesProcessIdCertificateRoute
  ProcessesProcessIdCompletedRoute: typeof ProcessesProcessIdCompletedRoute
  ProcessesProcessIdHistoryRoute: typeof ProcessesProcessIdHistoryRoute
  ProcessesProcessIdIndexRoute: typeof ProcessesProcessIdIndexRoute
}

const ProcessesProcessIdRouteChildren: ProcessesProcessIdRouteChildren = {
  ProcessesProcessIdCertificateRoute: ProcessesProcessIdCertificateRoute,
  ProcessesProcessIdCompletedRoute: ProcessesProcessIdCompletedRoute,
  ProcessesProcessIdHistoryRoute: ProcessesProcessIdHistoryRoute,
  ProcessesProcessIdIndexRoute: ProcessesProcessIdIndexRoute,
}

const ProcessesProcessIdRouteWithChildren =
  ProcessesProcessIdRoute._addFileChildren(ProcessesProcessIdRouteChildren)

interface ProcessesNewRouteChildren {
  ProcessesNewAnalyzingRoute: typeof ProcessesNewAnalyzingRoute
  ProcessesNewApprovedRoute: typeof ProcessesNewApprovedRoute
  ProcessesNewClassificationRoute: typeof ProcessesNewClassificationRoute
  ProcessesNewDeclarationRoute: typeof ProcessesNewDeclarationRoute
  ProcessesNewDocumentsRoute: typeof ProcessesNewDocumentsRoute
  ProcessesNewEstablishmentRoute: typeof ProcessesNewEstablishmentRoute
  ProcessesNewInspectionRoute: typeof ProcessesNewInspectionRoute
  ProcessesNewPaymentRoute: typeof ProcessesNewPaymentRoute
  ProcessesNewProcessingRoute: typeof ProcessesNewProcessingRoute
  ProcessesNewProtocolRoute: typeof ProcessesNewProtocolRoute
  ProcessesNewRequestRoute: typeof ProcessesNewRequestRoute
  ProcessesNewRequirementsRoute: typeof ProcessesNewRequirementsRoute
  ProcessesNewResponsibleRoute: typeof ProcessesNewResponsibleRoute
  ProcessesNewResultRoute: typeof ProcessesNewResultRoute
  ProcessesNewReviewRoute: typeof ProcessesNewReviewRoute
  ProcessesNewSubmitRoute: typeof ProcessesNewSubmitRoute
  ProcessesNewValidationRoute: typeof ProcessesNewValidationRoute
  ProcessesNewIndexRoute: typeof ProcessesNewIndexRoute
}

const ProcessesNewRouteChildren: ProcessesNewRouteChildren = {
  ProcessesNewAnalyzingRoute: ProcessesNewAnalyzingRoute,
  ProcessesNewApprovedRoute: ProcessesNewApprovedRoute,
  ProcessesNewClassificationRoute: ProcessesNewClassificationRoute,
  ProcessesNewDeclarationRoute: ProcessesNewDeclarationRoute,
  ProcessesNewDocumentsRoute: ProcessesNewDocumentsRoute,
  ProcessesNewEstablishmentRoute: ProcessesNewEstablishmentRoute,
  ProcessesNewInspectionRoute: ProcessesNewInspectionRoute,
  ProcessesNewPaymentRoute: ProcessesNewPaymentRoute,
  ProcessesNewProcessingRoute: ProcessesNewProcessingRoute,
  ProcessesNewProtocolRoute: ProcessesNewProtocolRoute,
  ProcessesNewRequestRoute: ProcessesNewRequestRoute,
  ProcessesNewRequirementsRoute: ProcessesNewRequirementsRoute,
  ProcessesNewResponsibleRoute: ProcessesNewResponsibleRoute,
  ProcessesNewResultRoute: ProcessesNewResultRoute,
  ProcessesNewReviewRoute: ProcessesNewReviewRoute,
  ProcessesNewSubmitRoute: ProcessesNewSubmitRoute,
  ProcessesNewValidationRoute: ProcessesNewValidationRoute,
  ProcessesNewIndexRoute: ProcessesNewIndexRoute,
}

const ProcessesNewRouteWithChildren = ProcessesNewRoute._addFileChildren(
  ProcessesNewRouteChildren,
)

interface ProcessesRouteChildren {
  ProcessesProcessIdRoute: typeof ProcessesProcessIdRouteWithChildren
  ProcessesAvcbRoute: typeof ProcessesAvcbRoute
  ProcessesNewRoute: typeof ProcessesNewRouteWithChildren
}

const ProcessesRouteChildren: ProcessesRouteChildren = {
  ProcessesProcessIdRoute: ProcessesProcessIdRouteWithChildren,
  ProcessesAvcbRoute: ProcessesAvcbRoute,
  ProcessesNewRoute: ProcessesNewRouteWithChildren,
}

const ProcessesRouteWithChildren = ProcessesRoute._addFileChildren(
  ProcessesRouteChildren,
)

interface SignupRouteChildren {
  SignupCompanyRoute: typeof SignupCompanyRoute
  SignupCompanySuccessRoute: typeof SignupCompanySuccessRoute
  SignupIndividualRoute: typeof SignupIndividualRoute
  SignupIndividualSuccessRoute: typeof SignupIndividualSuccessRoute
  SignupTechnicalResponsibleRoute: typeof SignupTechnicalResponsibleRoute
  SignupTechnicalResponsibleSuccessRoute: typeof SignupTechnicalResponsibleSuccessRoute
  SignupIndexRoute: typeof SignupIndexRoute
}

const SignupRouteChildren: SignupRouteChildren = {
  SignupCompanyRoute: SignupCompanyRoute,
  SignupCompanySuccessRoute: SignupCompanySuccessRoute,
  SignupIndividualRoute: SignupIndividualRoute,
  SignupIndividualSuccessRoute: SignupIndividualSuccessRoute,
  SignupTechnicalResponsibleRoute: SignupTechnicalResponsibleRoute,
  SignupTechnicalResponsibleSuccessRoute:
    SignupTechnicalResponsibleSuccessRoute,
  SignupIndexRoute: SignupIndexRoute,
}

const SignupRouteWithChildren =
  SignupRoute._addFileChildren(SignupRouteChildren)

interface TriageRouteChildren {
  TriageProcessIdRoute: typeof TriageProcessIdRoute
  TriageIndexRoute: typeof TriageIndexRoute
}

const TriageRouteChildren: TriageRouteChildren = {
  TriageProcessIdRoute: TriageProcessIdRoute,
  TriageIndexRoute: TriageIndexRoute,
}

const TriageRouteWithChildren =
  TriageRoute._addFileChildren(TriageRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AnalysisRoute: AnalysisRouteWithChildren,
  ClassifierRoute: ClassifierRoute,
  CompaniesRoute: CompaniesRouteWithChildren,
  DashboardRoute: DashboardRoute,
  DocumentsRoute: DocumentsRoute,
  FirstAccessRoute: FirstAccessRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  InspectionsRoute: InspectionsRouteWithChildren,
  MapRoute: MapRoute,
  NotificationsRoute: NotificationsRoute,
  ProcessesRoute: ProcessesRouteWithChildren,
  PublicConsultationRoute: PublicConsultationRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRouteWithChildren,
  TriageRoute: TriageRouteWithChildren,
  TriagemProcessoIdRoute: TriagemProcessoIdRoute,
  TriagemIndexRoute: TriagemIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
